# Generated by Django 5.0.2 on 2024-02-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
