# Generated by Django 5.0.2 on 2024-02-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_author_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('adress', models.TextField()),
            ],
        ),
    ]
