# Generated by Django 5.0.2 on 2024-02-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='Author_name',
        ),
    ]
