# Generated by Django 5.0.2 on 2024-02-27 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_name_author_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author_name',
            new_name='name',
        ),
    ]
